version: '3.8'
services:
  php-apache-environment:
    image: erni15/kuis3
    container_name: php-apache3
    depends_on:
      - db
    volumes:
      - ./hospital:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend

  db:
    container_name: db3
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hms
    ports:
      - "3300:3306"
    volumes:
      - db:/var/lib/mysql
      - ./SQLFile/hms.sql:/docker-entrypoint-initdb.d/hms.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24